"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 08:51:02
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('cache_hits', sa.Integer(), nullable=False),
    sa.Column('ms_total', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'day')
    )
    op.create_table('audio_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('accent', sa.String(length=32), nullable=True),
    sa.Column('speaker', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_page', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('mime', sa.String(length=32), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256'),
    sa.UniqueConstraint('source_url')
    )
    op.create_table('card_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('draft', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('published_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dictionary_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('include_audio', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('checks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_values',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('lemma', sa.String(length=128), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.Column('field', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('missing', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_language', 'lemma', 'native_language', 'field', name='uq_field_value')
    )
    op.create_table('image_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_image_id', sa.Text(), nullable=False),
    sa.Column('page_url', sa.Text(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('license_code', sa.String(length=32), nullable=True),
    sa.Column('license_url', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mime', sa.String(length=32), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('phash', sa.String(length=32), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('safety_status', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('words', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('checkpoint', sa.Integer(), nullable=False),
    sa.Column('counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_of', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retry_of'], ['import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status', 'import_jobs', ['status', 'created_at'], unique=False)
    op.create_table('languages',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('native_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('localized_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'language')
    )
    op.create_table('missing_lexeme_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('lemma', sa.String(length=128), nullable=False),
    sa.Column('pos', sa.String(length=16), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_language', 'lemma', 'pos')
    )
    op.create_table('source_lookups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('lemma', sa.String(length=128), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.Column('field', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('looked_up_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_language', 'lemma', 'native_language', 'field', 'source', name='uq_lookup')
    )
    op.create_table('source_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.Column('field', sa.String(length=48), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('max_items', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_test', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_language', 'native_language', 'field')
    )
    op.create_table('sources',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('license', sa.Text(), nullable=False),
    sa.Column('attribution', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('implemented', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('synsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('pos', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id')
    )
    op.create_table('tatoeba_links',
    sa.Column('a', sa.BigInteger(), nullable=False),
    sa.Column('b', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('a', 'b')
    )
    op.create_table('user_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('lemma', sa.String(length=128), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.Column('field', sa.String(length=48), nullable=False),
    sa.Column('items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_language', 'lemma', 'native_language', 'field', name='uq_override')
    )
    op.create_table('wordlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('words', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language', 'name')
    )
    op.create_table('card_template_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('layout', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['card_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_attempts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('lemma', sa.String(length=128), nullable=False),
    sa.Column('field', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'lemma', 'field', 'source')
    )
    op.create_index('ix_attempts_job_status', 'import_attempts', ['job_id', 'status'], unique=False)
    op.create_table('import_errors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('lemma', sa.String(length=128), nullable=False),
    sa.Column('field', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('error_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_record_id', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_errors_job', 'import_errors', ['job_id'], unique=False)
    op.create_table('import_job_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_logs_job', 'import_job_logs', ['job_id', 'id'], unique=False)
    op.create_table('import_job_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Integer(), nullable=False),
    sa.Column('missing', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('retried', sa.Integer(), nullable=False),
    sa.Column('ms_total', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'field', 'source')
    )
    op.create_table('language_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['native_language'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['target_language'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_language', 'native_language')
    )
    op.create_table('lexemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('lemma', sa.String(length=128), nullable=False),
    sa.Column('normalized', sa.String(length=128), nullable=False),
    sa.Column('pos', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cefr', sa.String(length=4), nullable=True),
    sa.Column('zipf', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language', 'normalized', 'pos', name='uq_lexeme')
    )
    op.create_index('ix_lexemes_trgm', 'lexemes', ['normalized'], unique=False, postgresql_using='gin', postgresql_ops={'normalized': 'gin_trgm_ops'})
    op.create_table('semantic_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('synset_id', sa.Integer(), nullable=False),
    sa.Column('target_synset_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['synset_id'], ['synsets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_synset_id'], ['synsets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_capabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.Column('field', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['source'], ['sources.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'target_language', 'native_language', 'field')
    )
    op.create_table('source_policy_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('timeout_s', sa.Float(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=True),
    sa.Column('continue_on_failure', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['source_policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source'], ['sources.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'source')
    )
    op.create_index('ix_policy_steps_order', 'source_policy_steps', ['policy_id', 'position'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source'], ['sources.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_template_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['card_template_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etymologies',
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('root', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prefix', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('suffix', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('origin_language', sa.Text(), nullable=True),
    sa.Column('original_form', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lexeme_id')
    )
    op.create_table('etymology_translations',
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_ai', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lexeme_id', 'native_language')
    )
    op.create_table('field_candidates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('lemma', sa.String(length=128), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.Column('field', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('item_key', sa.Text(), nullable=False),
    sa.Column('slot', sa.Text(), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_record_id', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('license', sa.Text(), nullable=False),
    sa.Column('attribution', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('invalid_reason', sa.Text(), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_language', 'lemma', 'native_language', 'field', 'source', 'item_key', name='uq_candidate')
    )
    op.create_index('ix_candidates_word', 'field_candidates', ['target_language', 'lemma', 'native_language', 'field'], unique=False)
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=48), nullable=False),
    sa.Column('form', sa.String(length=128), nullable=False),
    sa.Column('normalized', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lexeme_id', 'field', 'form')
    )
    op.create_index('ix_forms_normalized', 'forms', ['normalized'], unique=False)
    op.create_table('lexeme_redirects',
    sa.Column('old_id', sa.Integer(), nullable=False),
    sa.Column('new_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['new_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('old_id')
    )
    op.create_table('missing_localization_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.Column('field', sa.String(length=48), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lexeme_id', 'native_language', 'field')
    )
    op.create_table('pronunciations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('accent', sa.String(length=32), nullable=True),
    sa.Column('audio_asset_id', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('senses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('sense_key', sa.String(length=40), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('synset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['synset_id'], ['synsets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lexeme_id', 'sense_key')
    )
    op.create_table('tatoeba_sentences',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tatoeba_lang_md5', 'tatoeba_sentences', ['lang', sa.literal_column('md5(text)')], unique=False)
    op.create_index('ix_tatoeba_tsv', 'tatoeba_sentences', [sa.literal_column("to_tsvector('simple'::regconfig, text)")], unique=False, postgresql_using='gin')
    op.create_table('definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sense_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sense_id'], ['senses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sense_id', 'language')
    )
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('sense_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.String(length=4), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_record_id', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sense_id'], ['senses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lexeme_id', 'text_hash')
    )
    op.create_table('field_provenance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('field_value_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('item_key', sa.Text(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['field_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_value_id'], ['field_values.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provenance_value', 'field_provenance', ['field_value_id'], unique=False)
    op.create_table('image_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sense_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('concept_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('image_asset_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['image_asset_id'], ['image_assets.id'], ),
    sa.ForeignKeyConstraint(['sense_id'], ['senses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lexeme_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('source_sense_id', sa.Integer(), nullable=True),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('target_lexeme_id', sa.Integer(), nullable=False),
    sa.Column('target_word', sa.String(length=128), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_sense_id'], ['senses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lexeme_id', 'relation', 'target_lexeme_id')
    )
    op.create_table('sense_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sense_id', sa.Integer(), nullable=False),
    sa.Column('image_asset_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('alt_native', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['image_asset_id'], ['image_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sense_id'], ['senses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sense_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sense_id', sa.Integer(), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_ai', sa.Boolean(), nullable=False),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sense_id'], ['senses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sense_id', 'native_language')
    )
    op.create_table('example_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('example_id', sa.Integer(), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_record_id', sa.Text(), nullable=True),
    sa.Column('is_ai', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['example_id'], ['examples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('example_id', 'native_language')
    )
    op.create_table('image_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sense_image_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sense_image_id'], ['sense_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relation_target_senses',
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.Column('sense_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['lexeme_relations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sense_id'], ['senses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relation_id', 'sense_id')
    )
    op.create_table('relation_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_ai', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['lexeme_relations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relation_id', 'native_language')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_translations')
    op.drop_table('relation_target_senses')
    op.drop_table('image_reviews')
    op.drop_table('example_translations')
    op.drop_table('sense_translations')
    op.drop_table('sense_images')
    op.drop_table('lexeme_relations')
    op.drop_table('image_candidates')
    op.drop_index('ix_provenance_value', table_name='field_provenance')
    op.drop_table('field_provenance')
    op.drop_table('examples')
    op.drop_table('definitions')
    op.drop_index('ix_tatoeba_tsv', table_name='tatoeba_sentences', postgresql_using='gin')
    op.drop_index('ix_tatoeba_lang_md5', table_name='tatoeba_sentences')
    op.drop_table('tatoeba_sentences')
    op.drop_table('senses')
    op.drop_table('pronunciations')
    op.drop_table('missing_localization_requests')
    op.drop_table('lexeme_redirects')
    op.drop_index('ix_forms_normalized', table_name='forms')
    op.drop_table('forms')
    op.drop_index('ix_candidates_word', table_name='field_candidates')
    op.drop_table('field_candidates')
    op.drop_table('etymology_translations')
    op.drop_table('etymologies')
    op.drop_table('card_template_sections')
    op.drop_table('source_snapshots')
    op.drop_index('ix_policy_steps_order', table_name='source_policy_steps')
    op.drop_table('source_policy_steps')
    op.drop_table('source_capabilities')
    op.drop_table('semantic_relations')
    op.drop_index('ix_lexemes_trgm', table_name='lexemes', postgresql_using='gin', postgresql_ops={'normalized': 'gin_trgm_ops'})
    op.drop_table('lexemes')
    op.drop_table('language_pairs')
    op.drop_table('import_job_steps')
    op.drop_index('ix_job_logs_job', table_name='import_job_logs')
    op.drop_table('import_job_logs')
    op.drop_index('ix_errors_job', table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index('ix_attempts_job_status', table_name='import_attempts')
    op.drop_table('import_attempts')
    op.drop_table('card_template_versions')
    op.drop_table('wordlists')
    op.drop_table('user_overrides')
    op.drop_table('tatoeba_links')
    op.drop_table('synsets')
    op.drop_table('sources')
    op.drop_table('source_policies')
    op.drop_table('source_lookups')
    op.drop_table('missing_lexeme_requests')
    op.drop_table('localized_labels')
    op.drop_table('languages')
    op.drop_index('ix_jobs_status', table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_table('image_assets')
    op.drop_table('field_values')
    op.drop_table('dictionary_releases')
    op.drop_table('card_templates')
    op.drop_table('audio_assets')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
