"""idempotency keys

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 09:00:48
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary_releases', sa.Column('idempotency_key', sa.String(length=80), nullable=True))
    op.create_unique_constraint('dictionary_releases_idempotency_key_key', 'dictionary_releases', ['idempotency_key'])
    op.add_column('import_jobs', sa.Column('idempotency_key', sa.String(length=80), nullable=True))
    op.create_unique_constraint('import_jobs_idempotency_key_key', 'import_jobs', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('import_jobs_idempotency_key_key', 'import_jobs', type_='unique')
    op.drop_column('import_jobs', 'idempotency_key')
    op.drop_constraint('dictionary_releases_idempotency_key_key', 'dictionary_releases', type_='unique')
    op.drop_column('dictionary_releases', 'idempotency_key')
    # ### end Alembic commands ###
