"""morphemes

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 14:48:43
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('morphemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('free', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lexeme_id', 'ordinal')
    )
    op.create_table('morpheme_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('morpheme_id', sa.Integer(), nullable=False),
    sa.Column('native_language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_ai', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['morpheme_id'], ['morphemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('morpheme_id', 'native_language')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('morpheme_translations')
    op.drop_table('morphemes')
    # ### end Alembic commands ###
